---
datacenter:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 10.215.27.98
        R2:
          ansible_host: 10.215.27.99
    # Example switch hosts
    # switches:
    #   hosts:
  vars:
    ansible_become_password: vnpro@321
    ansible_user: vnpro
    ansible_password: vnpro@123
    ansible_connection: network_cli
    ansible_become: "yes"   
    ansible_become_method: "enable"
    ansible_network_os: ios
