---
- name: Configure Router 1
  hosts: R1
  
  tasks:
    - name: Set IP
      ios_config:
        parents: "{{ item.int }}"
        lines:
          - no sh 
          - ip 192.168.{{ item.ip }} 255.255.255.0

      loop:
        - { ip: 1.1, int: Ethernet0/1 }
        - { ip: 12.1, int: Ethernet0/2 }
